version: "2"

services:

  plone:
    build: .
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
      - zeoserver
      - memcached
    environment:
      ZOPE_MODE: "zeo_client"
      TZ: "Europe/Copenhagen"
    volumes:
      - ./data:/data
      - ./src/:/plone/instance/src/
      - ./buildout.cfg:/plone/instance/buildout.cfg
    ports:
      - "8081:8080"
    entrypoint: sh -c "tail -f /dev/null"

  async:
    build: .
    labels:
      io.rancher.scheduler.affinity:host_label: cca=yes
    depends_on:
      - zeoserver
      - memcached
    environment:
      ZOPE_MODE: "zeo_async"
      TZ: "Europe/Copenhagen"
    volumes:
      - ./data:/data
    entrypoint: sh -c "tail -f /dev/null"

  memcached:
    image: memcached:1.4.35
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
    command:
      - "-m"
      - "2048"

  zeoserver:
    image: plone:4.3.10
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
    command:
      - zeoserver
    volumes:
      - ./data:/data
      - ./data/blobstorage:/data/blobstorage

