version: "2"

services:

  plone:
    build: ./docker/
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
      - zeo
      - memcached
    environment:
      TZ: "Europe/Copenhagen"
      ZEO_ADDRESS: "zeo:8080"
      ZOPE_MODE: "zeo_client"
    volumes:
      - ./src/:/plone/instance/src/
      - ./docker/custom.cfg:/plone/instance/custom.cfg
      # - ./data:/data
    ports:
      - "8085:8080"
    entrypoint: sh -c "tail -f /dev/null"

  memcached:
    image: memcached:1.4.35
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
    command:
      - "-m"
      - "2048"

  zeo:
    image: eeacms/plonesaas:5.1.5-67
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
      ZOPE_MODE: "zeo"
    command:
      - zeo
    volumes:
      - ./data:/data
      # - ./data/blobstorage:/data/blobstorage

  frontend:
    build: ./frontend
    environment:
      VOLTO_API_PATH: "http://localhost:8085/fise/"
      RAZZLE_API_PATH: "http://localhost:8085/fise/"
      PORT: "4000"
    ports:
      - "4000:4000"
      - "4001:4001"
    entrypoint: sh -c "tail -f /dev/null"
    volumes:
      - ./frontend:/app/fise

  # frontend:
  #   image: plone/volto:latest
  #   environment:
  #     VOLTO_API_PATH: "http://localhost:8085/Plone2/"
  #     RAZZLE_API_PATH: "http://localhost:8085/Plone2/"
  #   ports:
  #     - "3000:3000"
  #     - "3001:3001"
  #   entrypoint: sh -c "tail -f /dev/null"
