version: "2"

services:

  plone:
    build: ./docker/
    # image: kitconcept/plone.restapi:latest
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
      - zeo
      - memcached
    ports:
      - "8085:8080"
    # entrypoint: sh -c "tail -f /dev/null"
    environment:
      TZ: "Europe/Copenhagen"
      ZEO_ADDRESS: "zeo:8080"
      ZOPE_MODE: "zeo_client"
    volumes:
    - ./src/:/plone/instance/src/
    - ./docker/site.cfg:/plone/instance/site.cfg
    # - ./data:/data

  memcached:
    image: memcached:1.4.35
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
    command:
      - "-m"
      - "2048"

  zeo:
    image: eeacms/plonesaas:5.1.5-67
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
      ZOPE_MODE: "zeo"
    command:
      - zeo
    volumes:
      - ./data:/data
      # - ./data/blobstorage:/data/blobstorage

  frontend:
    build: ./frontend
    environment:
      RAZZLE_API_PATH: "http://localhost:8085/Plone"
      RAZZLE_INTERNAL_API_PATH: "http://plone:8080/Plone"
      PORT: "3000"
    ports:
      - "3000:3000"
      - "3001:3001"
    entrypoint: sh -c "tail -f /dev/null"
    # volumes:
    #   - ./frontend:/opt/fise

  volto:
    image: plone/volto:latest
    environment:
      RAZZLE_API_PATH: "http://localhost:8085/Plone"
      RAZZLE_INTERNAL_API_PATH: "http://plone:8080/Plone"
      PORT: "4300"
    ports:
      - "4300:4300"
      - "4301:4301"
    entrypoint: sh -c "tail -f /dev/null"

  restapi:
    image: kitconcept/plone.restapi:latest
    entrypoint: sh -c "tail -f /dev/null"
    # ports:
    #   - "8085:8080"

